### ISSUE TITLE
[QUESTION] will the patch code merged into upstream?

### ISSUE THREAD

**Issue by ultranity** [volcengine/veScale#17]
veScale includes two patch for pytorch and torchdistX, is or will there any submit PR to the upstream for the two patchs?

**Comment by lchang20** [comment]
Yes, the PRs are already submitted. After they are merged, we will bump up the dependences. 
I will include the links later.

**Comment by liwenchangbdbz** [comment]
Yes, the PRs are already submitted. After they are merged, we will bump up the dependences. 
I will include the links of those PRs later.

**Comment by JsBlueCat** [comment]
> veScale includes two patch for pytorch and torchdistX, is or will there any submit PR to the upstream for the two patchs?

hello, currently we have pushed some code to origin upsream, but it depends there merge

for torch:

- https://github.com/pytorch/pytorch/pull/122486 expand_as
- https://github.com/pytorch/pytorch/pull/116757 support dtensor local storage

for torchdistx:

- https://github.com/pytorch/torchdistx/pull/82
