### ISSUE TITLE
[QUESTION]`vescale.dtensor` vs "PyTorch DTensor"

### ISSUE THREAD

**Issue by GHGmc2** [volcengine/veScale#28]
Thanks for the work.

May I know what's the difference between `vescale.dtensor` and DTensor in torch?

Thanks!

**Comment by liwenchangbdbz** [comment]
https://github.com/volcengine/veScale/pull/8

**Comment by GHGmc2** [comment]
> #8 explained the difference.

Thanks for the info.

**Comment by leonardo0lyj** [comment]
https://github.com/volcengine/veScale/tree/main/python/vescale/dtensor#what-is-vescale-dtensor
