### ISSUE TITLE
[QUESTION] how and where to use multi-node trace profiler in paper of megascale 

### ISSUE THREAD

**Issue by oliverYoung2001** [volcengine/veScale#37]
I read the paper of megascale. And I find that the multi-node trace profiler is really useful for me. Thus I want to know how and where to use this tool ?
<img width="1175" alt="Screenshot 2024-05-24 at 15 09 56" src="https://github.com/volcengine/veScale/assets/55433595/ebb8542c-cd77-4ff0-b853-1faf5b6e92ba">

**Comment by pengyanghua** [comment]
@oliverYoung2001 Hi, the cuda event monitor tool will be released by the end of July, as said in the README.md.

**Comment by GHGmc2** [comment]
> @oliverYoung2001 Hi, the cuda event monitor tool will be released by the end of July, as said in the README.md.

any update?

**Comment by leonardo0lyj** [comment]
Hi all, here it is: https://github.com/volcengine/veScale/tree/main/vescale/ndtimeline
