### ISSUE TITLE
[QUESTION] How flexible is the veScale checkpoint

### ISSUE THREAD

**Issue by Dream-Seeker123** [volcengine/veScale#43]
I have some questions regarding load-time checkpoint resharding:

1. Does it only support DModule and DistributedOptimizer? How can I integrate checkpoint resharding with Megatron and DeepSpeed?
2. Does it support ZeRO-1, ZeRO-2, ZeRO-3, and sequence parallelism?

**Comment by Dream-Seeker123** [comment]
@MingjiHan99 I would appreciate it if you could answer the question.

**Comment by Dream-Seeker123** [comment]
Would someone be able to assist in answering this question?

**Comment by MingjiHan99** [comment]
@Dream-Seeker123 
Thanks for your interest in veScale project !

Does it only support DModule and DistributedOptimizer? How can I integrate checkpoint resharding with Megatron and DeepSpeed?
By August 6, 2024, the veScale checkpoint supports both DModule and DistributedOptimizer. Support for BasicOptimizer will be added later. The primary focus of the veScale checkpoint is to provide distributed checkpointing and auto-resharding capabilities to veScale.   
If you are interested in a checkpoint system which supports multiple training frameworks, you are welcome to check our latest research work: ByteCheckpoint: A Unified Checkpointing System for LLM Development on https://arxiv.org/abs/2407.20143.   

Does it support ZeRO-1, ZeRO-2, ZeRO-3, and sequence parallelism?   
By August 6, 2024, the veScale distributed optimizer uses ZeRO-2, thereby supporting both ZeRO-1 and ZeRO-2.   

It appears you are an expert in MLSys. I would like to have further discussions as long as you could use a GitHub account or email associated with an institution or organization.
