### ISSUE TITLE
[QUESTION]How is vescale zero2 implemented? 

### ISSUE THREAD

**Issue by starstream** [volcengine/veScale#54]
How is vescale zero2 implemented? Is the distributed optimizer of megatron zero2?

**Comment by starstream** [comment]
reduce-scatter grad buffer seems to work in the same way when using distributed optimizer

**Comment by MackZackA** [comment]
Thank you for your interest in veScale DistributedOptimizer!
Our DistributedOptimizer differs from Megatron's Zero2 in the following ways:
1. more refined support of in-house distributed optimizer mechanism with our save/load state specs and execution handlers
2. support our own DDP module and parallelization mechanisms as well as ZeRO handlers dependent on DDP.

If you have any specific question, feel free to comment below.

**Comment by starstream** [comment]
> Thank you for your interest in veScale DistributedOptimizer! Our DistributedOptimizer differs from Megatron's Zero2 in the following ways:
> 
> 1. more refined support of in-house distributed optimizer mechanism with our save/load state specs and execution handlers
> 2. support our own DDP module and parallelization mechanisms as well as ZeRO handlers dependent on DDP.
> 
> If you have any specific question, feel free to comment below.
----

I understand megatron as zero1, so I'm a little confused

**Comment by MackZackA** [comment]
Thank you for clarifying the typo. Megatron supports only zero 1, as it only shards optimizer state and no grads.

**Comment by starstream** [comment]
> Thank you for clarifying the typo. Megatron supports only zero 1, as it only shards optimizer state and no grads.

vescale supports zero2, but I can't find any implementation for it. Can you tell me where the code is.
